- name: Configure HAProxy as Load Balancer
  hosts: 127.0.0.1
  become: yes
  vars:
    haproxy_cfg_template: templates/haproxy.cfg.j2
    haproxy_cfg_dest: /etc/haproxy/haproxy.cfg

  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Generate self-signed certificate
      import_tasks: tasks/generate_selfsigned_cert.yml

    - name: Copy HAProxy config from template
      template:
        src: "{{ haproxy_cfg_template }}"
        dest: "{{ haproxy_cfg_dest }}"
        owner: root
        group: root
        mode: '0644'

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

