- name: Deploy Flask App con Docker
  hosts: all
  become: yes
  gather_facts: no

  vars:
    container_count: 3 # Numero di container per ogni server
    base_port: 5000 # Porta di partenza per i container

  tasks:
    - name: Aggiorna i server
      apt:
        update_cache: true
        upgrade: dist
    
    - name: Permessi di lettura ed esecuzione
      file:
        path: /root/ansible
        recurse: yes
        mode: '0755'

    - name: Installare Docker
      apt:
        name: docker.io
        state: present

    - name: Avviare Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Costruire l'immagine Docker
      command: docker build -t flask_app /root/ansible/
      register: docker_install_status 

    - name: Avviare il container Docker
      loop: "{{ range(0, container_count) | list }}"
      command: docker run -d -p {{ base_port + item }}:5000 --name flask_app_{{ item }} flask_app
      when: docker_install_status.rc == 0


